//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_XRTLogging : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean trigger_touch_bool
        {
            get
            {
                return SteamVR_Actions.xRTLogging_trigger_touch_bool;
            }
        }
        
        public virtual SteamVR_Action_Boolean trigger_click_bool
        {
            get
            {
                return SteamVR_Actions.xRTLogging_trigger_click_bool;
            }
        }
        
        public virtual SteamVR_Action_Single trigger_pull_float
        {
            get
            {
                return SteamVR_Actions.xRTLogging_trigger_pull_float;
            }
        }
        
        public virtual SteamVR_Action_Boolean grip_touch_bool
        {
            get
            {
                return SteamVR_Actions.xRTLogging_grip_touch_bool;
            }
        }
        
        public virtual SteamVR_Action_Boolean grip_click_bool
        {
            get
            {
                return SteamVR_Actions.xRTLogging_grip_click_bool;
            }
        }
        
        public virtual SteamVR_Action_Single grip_pull_float
        {
            get
            {
                return SteamVR_Actions.xRTLogging_grip_pull_float;
            }
        }
        
        public virtual SteamVR_Action_Boolean system_touch_bool
        {
            get
            {
                return SteamVR_Actions.xRTLogging_system_touch_bool;
            }
        }
        
        public virtual SteamVR_Action_Boolean system_click_bool
        {
            get
            {
                return SteamVR_Actions.xRTLogging_system_click_bool;
            }
        }
        
        public virtual SteamVR_Action_Boolean touchpad_touch_bool
        {
            get
            {
                return SteamVR_Actions.xRTLogging_touchpad_touch_bool;
            }
        }
        
        public virtual SteamVR_Action_Boolean touchpad_click_bool
        {
            get
            {
                return SteamVR_Actions.xRTLogging_touchpad_click_bool;
            }
        }
        
        public virtual SteamVR_Action_Vector2 touchpad_position_vector2
        {
            get
            {
                return SteamVR_Actions.xRTLogging_touchpad_position_vector2;
            }
        }
        
        public virtual SteamVR_Action_Boolean menu_click_bool
        {
            get
            {
                return SteamVR_Actions.xRTLogging_menu_click_bool;
            }
        }
        
        public virtual SteamVR_Action_Boolean joystick_touch_bool
        {
            get
            {
                return SteamVR_Actions.xRTLogging_joystick_touch_bool;
            }
        }
        
        public virtual SteamVR_Action_Boolean joystick_click_bool
        {
            get
            {
                return SteamVR_Actions.xRTLogging_joystick_click_bool;
            }
        }
        
        public virtual SteamVR_Action_Vector2 joystick_position_vector2
        {
            get
            {
                return SteamVR_Actions.xRTLogging_joystick_position_vector2;
            }
        }
        
        public virtual SteamVR_Action_Boolean buttonx_touch_bool
        {
            get
            {
                return SteamVR_Actions.xRTLogging_buttonx_touch_bool;
            }
        }
        
        public virtual SteamVR_Action_Boolean buttonx_click_bool
        {
            get
            {
                return SteamVR_Actions.xRTLogging_buttonx_click_bool;
            }
        }
        
        public virtual SteamVR_Action_Boolean buttony_touch_bool
        {
            get
            {
                return SteamVR_Actions.xRTLogging_buttony_touch_bool;
            }
        }
        
        public virtual SteamVR_Action_Boolean buttony_click_bool
        {
            get
            {
                return SteamVR_Actions.xRTLogging_buttony_click_bool;
            }
        }
    }
}
